apiVersion: v1
kind: Pod
metadata:
  name: sandbox-pod-019ef519-b572-746d-bab1-b2385dc50396
  labels:
    app: sandbox
    sandboxId: 019ef519-b572-746d-bab1-b2385dc50396
spec:
  volumes:
    - name: workspace-volume
      emptyDir: {}
  containers:
    - name: sandbox-container-019ef519-b572-746d-bab1-b2385dc50396
      image: template:v2
      imagePullPolicy: IfNotPresent
      command: ["/bin/sh", "-c"]
      args:
        - "cp -r /template/. /workspace && cd /workspace && npm run dev -- --host 0.0.0.0"
      volumeMounts:
        - name: workspace-volume
          mountPath: /workspace
      ports:
        - containerPort: 5173
          name: http
    - name: agent-container
      image: agent:v3
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 8080
          name: http
      volumeMounts:
        - name: workspace-volume
          mountPath: /workspace
