apiVersion: skaffold/v4beta13
kind: Config

build:
  artifacts:
    - image: auth
      context: auth
      docker:
        dockerfile: dockerfile

  platform:
    - linux/amd64 # your ec2 instance
    
    - image: notification  # <ACCOUNT_ID>.dkr.ecr.<REGION>.amazonaws.com/notification:dev
      context: notification
      docker:
        dockerfile: dockerfile


    - image: ai-orchestration # <ACCOUNT_ID>.dkr.ecr.<REGION>.amazonaws.com/ai-orchestration:dev
      context: ai-orchestration
      docker:
        dockerfile: dockerfile


    - image: agent # <ACCOUNT_ID>.dkr.ecr.<REGION>.amazonaws.com/agent:dev
      context: sandbox/agent
      docker:
        dockerfile: dockerfile

    - image: router # <ACCOUNT_ID>.dkr.ecr.<REGION>.amazonaws.com/router:dev
      context: sandbox/router
      docker:
        dockerfile: dockerfile

    - image: sync-agent # <ACCOUNT_ID>.dkr.ecr.<REGION>.amazonaws.com/sync-agent:dev
      context: sandbox/sync-agent
      docker:
        dockerfile: Dockerfile

    - image: main-sandbox # <ACCOUNT_ID>.dkr.ecr.<REGION>.amazonaws.com/main-sandbox:dev
      context: sandbox/server
      docker:
        dockerfile: dockerfile

    - image: template # <ACCOUNT_ID>.dkr.ecr.<REGION>.amazonaws.com/template:dev
      context: sandbox/template
      docker:
        dockerfile: dockerfile

manifests:
  rawYaml:
    - k8s/secrets.yml
    - k8s/auth-deployment.yml
    - k8s/auth-service.yml
    - k8s/ai-deployment.yml
    - k8s/ai-service.yml
    - k8s/ingress.yml
    - k8s/router-deployment.yml
    - k8s/router-service.yml
    - k8s/sandbox-deployment.yml
    - k8s/sandbox-service.yml
    - k8s/notification.deployment.yml
    - k8s/notification-service.yml